# $FreeBSD$

KMOD=   procfs	
SRCS=	procfs.h \
	procfs_dbregs.c \
	procfs_fpregs.c \
	procfs_map.c \
	procfs_mem.c \
	procfs_note.c \
	procfs_osrel.c \
	procfs_regs.c \
	procfs_rlimit.c \
	procfs_status.c \
	procfs_type.c \
	procfs.c

.include <bsd.kmod.mk>

